### ISSUE TITLE
Figure out why the newest few sets haven't auto-updated.

### ISSUE THREAD

**Issue by KingSupernova31** [KingSupernova31/RulesGuru#140]
MTGJSON probably broke something again. Unstable cards haven't been added to the RG database.

Error message:

TypeError: Cannot read property 'legalities' of undefined
    at writeCardList (/var/www/rulesguru.net/updateDataFiles.js:337:20)
    at disperseFiles (/var/www/rulesguru.net/updateDataFiles.js:419:3)
    at updateAllCards (/var/www/rulesguru.net/updateDataFiles.js:320:2)
    at WriteStream.<anonymous> (/var/www/rulesguru.net/updateDataFiles.js:562:5)
    at WriteStream.emit (node:events:378:20)
    at emitCloseNT (node:internal/streams/destroy:169:10)
    at processTicksAndRejections (node:internal/process/task_queues:80:21)

**Comment by KingSupernova31** [comment]
Found the problem.
![image](https://user-images.githubusercontent.com/27539004/210694322-4728265f-b7a6-4ec5-90a8-e123013b9e32.png)

**Comment by KingSupernova31** [comment]
This has been fixed in the laziest possible way. (I just removed Unquenchable Fury's broken card entry from the files.)
