### ISSUE TITLE
Question 476 is bugged

### ISSUE THREAD

**Issue by KingSupernova31** [KingSupernova31/RulesGuru#177]
Expanding the answer results in
```
Uncaught TypeError: Cannot read properties of undefined (reading 'filter')
    at populateCardDisplayArea (rulesguru.js:280:72)
    at displayCurrentQuestion (rulesguru.js:263:2)
    at rulesguru.js:116:4
    at httpRequest.onload (rulesguru.js:168:5)
```

**Comment by KingSupernova31** [comment]
Maybe also 5643

**Comment by KingSupernova31** [comment]
AND 11

**Comment by KingSupernova31** [comment]
477

**Comment by KingSupernova31** [comment]
1125
5834
